//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Shared__Layout_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Shared__Layout_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalCloud.Resources.Views.Shared._Layout.en", typeof(Views_Shared__Layout_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2025 Secondary School of Technical Engineering Jecna.
        /// </summary>
        internal static string _copy__2025_SPŠE_Ječná___Cloudové_úložiště {
            get {
                return ResourceManager.GetString("&copy; 2025 SPŠE Ječná - Cloudové úložiště", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalCloud.
        /// </summary>
        internal static string Cloudové_úložiště {
            get {
                return ResourceManager.GetString("Cloudové úložiště", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Domů {
            get {
                return ResourceManager.GetString("Domů", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Kalendář {
            get {
                return ResourceManager.GetString("Kalendář", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossword finder.
        /// </summary>
        internal static string Křížovkářský_slovník {
            get {
                return ResourceManager.GetString("Křížovkářský slovník", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Moje_obrázky {
            get {
                return ResourceManager.GetString("Moje obrázky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My documents.
        /// </summary>
        internal static string Moje_soubory {
            get {
                return ResourceManager.GetString("Moje soubory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string Ochrana_soukromí {
            get {
                return ResourceManager.GetString("Ochrana soukromí", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out....
        /// </summary>
        internal static string Odhlásit_se___ {
            get {
                return ResourceManager.GetString("Odhlásit se...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prague Integrated Trasport.
        /// </summary>
        internal static string Odjezdy_PID {
            get {
                return ResourceManager.GetString("Odjezdy PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Player.
        /// </summary>
        internal static string Přehrávač_skladeb {
            get {
                return ResourceManager.GetString("Přehrávač skladeb", resourceCulture);
            }
        }
    }
}
